# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tarea07' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tarea07
  pod 'Amplify'
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'SCLAlertView'

end
